apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: cmaj-legend-app
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/cmaj/legend/legend-app:{{.VERSION}}'
  local: {}
deploy:
  kubectl:
    manifests:
      kubernetes/templates/DeployNewArtifact.yaml
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/cmaj/legend/legend-app:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: cmaj-legend
        chartPath: charts/cmaj-legend
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/cmaj/legend/legend-app'
          image.tag: '{{.DIGEST_HEX}}'
